[package]
name = "money-transfer"
version = "0.1.0"
authors = ["Jakub Zimny <zimny.jot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.7", features = ["v4"] }